## To implement
# pipenv install pylint black pytest --dev
# pip install pre-commit
# pre-commit autoupdate
# pre-commit run --all-files

repos:

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'  # Utilise la dernière révision
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: '24.4.2'  # Utilise la dernière révision
    hooks:
      - id: black

  - repo: local


    hooks:
      - id: pytest
        name: pytest
        entry: pipenv run python -m pytest test
        language: system
        types: [python]
        pass_filenames: false

exclude: '^$'  # Inclure tous les fichiers