## To implement
# pipenv install pylint black pytest --dev
# pip install pre-commit
# pre-commit autoupdate
repos:


  - repo: https://github.com/psf/black
    rev: '24.4.2'  # Utilise la dernière révision
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -v
        language: system
        types: [python]
        pass_filenames: false

exclude: '^$'  # Inclure tous les fichiers

