name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Pipenv and dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Create .env file
        run: |
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "T_MAX=${{ secrets.T_MAX }}" >> .env
          echo "T_MIN=${{ secrets.T_MIN }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Run tests
        run: pipenv run python -m pytest test

      - name: Lint and format code
        run: |
          pipenv run pylint src test
          pipenv run black src test

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs_container:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs_container:latest ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs_container:${{ github.run_number }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Push Docker image to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs_container:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs_container:${{ github.run_number }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
